infer_eval_metric: True
detect_and_drop_id_column: False
task_preprocessors_timeout: 3600
time_limit: 14400
save_artifacts:
  enabled: False
  append_timestamp: True
  path: "./artifacts"
feature_transformers:
  enabled_models: []
  models:
    CAAFE:
      _target_: fedotllm.transformer.feature_transformers.caafe.CAAFETransformer
      eval_model: lightgdm
      llm_provider: ${llm.provider}
      llm_model: ${llm.model}
      num_iterations: 5
      optimization_metric: roc
automl:
  enabled: "autogluon"
  autogluon:
    predictor_init_kwargs: {}
    predictor_fit_kwargs:
      presets: best_quality
  fedot:
    predictor_init_kwargs:
      preset: best_quality
    predictor_fit_kwargs: {}
llm:
  provider: openai
  model: gpt-4o-mini
  base_url: https://models.inference.ai.azure.com
  api_key: ${env:FEDOTLLM_LLM_API_KEY}
  max_tokens: 512
  temperature: 0
  verbose: True