time_limit: 600
automl:
  autogluon:
    predictor_fit_kwargs:
      presets: medium_quality
  fedot:
    predictor_init_kwargs:
      preset: fast_train
  fedot_ind:
    predictor_init_kwargs:
      preset: fast_train
